### PR TITLE
Made some QOL changes and (tried) to make a rigged version, will comment that one later

### PR DESCRIPTION
**Pull request by AstroOrbis**

### CODE REVIEW

**Review by Alawal — APPROVED** [review]
I have successfully approved your Pull request, thanks!

**Comment by AstroOrbis** [comment]
On line 22 (i may have forgotten the line) there's an error I can't seem to fix, can you help?

**Comment by Alawal** [comment]
> On line 22 (i may have forgotten the line) there's an error I can't seem to fix, can you help?

I will give it a look.

**Comment by Alawal** [comment]
> On line 22 (i may have forgotten the line) there's an error I can't seem to fix, can you help?

Got you. Have been fixed and merged.
However, I have deleted your Shell file, the same you did with it is also possible in Python,
it looks even better in Python and is easier to understand - it's the main.py now.

Thanks for your Pull Request, have a nice day!
ARealWant

**Pull request merged**
